Repository hobbyloop/hobbyloop-iOS, pull requests merged in 2023-09, with the labels that each got.

#25 내 정보 수정 화면 UI 구현
  App/Sources/Presentation/MyPage/CouponPurchaseHistoryGroupItemView.swift
  App/Sources/Presentation/MyPage/MyPageViewController.swift
  App/Sources/Presentation/MyPage/UserInfoEditViewController.swift
  Core/HPCommon/Sources/SignUp/SignUpInfoView.swift
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/Arrow/leftarrow.imageset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/Arrow/leftarrow.imageset/leftarrow.svg
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/plus.imageset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/plus.imageset/plus.svg
Labels: ✨ Feature

#26 설정 화면 UI 구현
  App/Sources/Presentation/MyPage/Settings/SettingsViewController.swift
  App/Sources/Presentation/MyPage/UserInfoEdit/UserInfoEditViewController.swift
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/lightButtonBackground.colorset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/switchBackground.colorset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/Info/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/Info/info.imageset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/Info/info.imageset/Group 4504.svg
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/onboardingImage4.imageset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/onboardingImage4.imageset/onbaording4 2.png
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/onboardingImage4.imageset/onboarding4 3.png
  UI/HPCommonUI/Resources/Assets.xcassets/HPImage/onboardingImage4.imageset/onboarding4.png
  UI/HPCommonUI/Sources/Common/Switch/HPSwitch.swift
Labels: ✨ Feature, 🤩 남건

#28 [REFACTOR] HPCalendarView UI 및 내부 로직 변경
  App/Sources/Presentation/Home/Component/Cell/CalendarCell.swift
  Core/HPExtensions/Sources/Date+Extensions.swift
  Core/HPExtensions/Sources/ReactorKit+Extensions.swift
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/lightPeach.colorset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/linen.colorset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/peach.colorset/Contents.json
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/HPCalendarBubbleDayCell.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/HPCalendarDayCell.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/HPCalendarWeekCell.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/Reactor/HPCalendarBubbleDayCellReactor.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/Reactor/HPCalendarDayCellReactor.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/Cell/Reactor/HPCalendarWeekCellReactor.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/DelegateProxy/HPCalendarDelgateProxy.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/DelegateProxy/HPCalendarInterface.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/DelegateProxy/HPCalendarProxyBinder.swift
  UI/HPCommonUI/Sources/Common/Calendar/Component/ReusableView/HPCalendarWeekReusableView.swift
  UI/HPCommonUI/Sources/Common/Calendar/DataSources/CalendarSection.swift
  UI/HPCommonUI/Sources/Common/Calendar/HPCalendarContentView.swift
  UI/HPCommonUI/Sources/Common/Calendar/HPCalendarView.swift
  UI/HPCommonUI/Sources/Common/Calendar/Reactor/HPCalendarViewReactor.swift
Labels: 🔨 Refactor, 🤩 도현

#36 [REFACTOR] HPNavigationController 화면 단위 별 NavigationItem Setting
  App/Sources/Application/AppDelegate.swift
  App/Sources/Application/SceneDelegate.swift
  App/Sources/Presentation/Main/TabBar/CustomTabBarController.swift
  App/Sources/Presentation/Navigation/HPNavigationController.swift
  Core/HPExtensions/Sources/Notification+Extensions.swift
  UI/HPCommonUI/Sources/Common/Calendar/Reactor/HPCalendarViewReactor.swift
Labels: 🔨 Refactor, 🤩 도현
