Repository hobbyloop/hobbyloop-iOS, pull requests merged in 2023-06, with the labels that each got.

#11 Fix/setup network layer
  Core/HPDomain/Sources/Base/BaseEntity.swift
  Core/HPDomain/Sources/empty.txt
  Core/HPNetwork/Resources/Model/TestModel.swift
  Core/HPNetwork/Resources/Network.swift
  Core/HPNetwork/Sources/Base/APIClient.swift
  Core/HPNetwork/Sources/Base/HPParameterType.swift
  Core/HPNetwork/Sources/Base/Router.swift
  Core/HPNetwork/Sources/Test/Model/TestRequest.swift
  Core/HPNetwork/Sources/Test/Model/TestResponse.swift
  Core/HPNetwork/Sources/Test/TestTarget.swift
Labels: 🔨 Refactor, 🤩 도현

#14 이용권 UI 구현
  App/Sources/MyPageViewController.swift
  Core/HPNetwork/Resources/empty.txt
  UI/HPCommonUI/Project.swift
  UI/HPCommonUI/Sources/CouponView.swift
Labels: ✨ Feature, 🤩 남건

#17 [FEAT] Social Login API 연동 및 UI 개선 작업
  App/Hobbyloop.entitlements
  App/Sources/Application/AppDelegate.swift
  App/Sources/Presentation/Login/LoginViewController.swift
  App/Sources/Presentation/Login/Reactor/LoginViewReactor.swift
  App/Sources/Presentation/Login/Repository/LoginViewRepository.swift
  App/Sources/Presentation/SignUp/Reactor/SignUpViewReactor.swift
  App/Sources/Presentation/SignUp/SignUpViewController.swift
  Core/HPCommon/Project.swift
  Core/HPCommon/Sources/Account/AccountType.swift
  Core/HPCommon/Sources/SignUp/SignUpInfoView.swift
  Core/HPCommon/Sources/SignUp/SignUpTermsView.swift
  Core/HPCommon/Sources/Util/HapticUtil.swift
  Core/HPExtensions/Project.swift
  Core/HPExtensions/Sources/String+Extensions.swift
  Core/HPExtensions/Sources/UIApplication+Extensions.swift
  Core/HPExtensions/Sources/UIKit/UILabel+Extensions.swift
  Core/HPExtensions/Sources/UIKit/UIView+Extensions.swift
  Core/HPExtensions/Sources/UserDefaults+Extensions.swift
  Core/HPFoundation/Sources/empty.txt
  Core/HPNetwork/Sources/Base/APIClient.swift
  Core/HPNetwork/Sources/Routers/AccountRouter.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/lightBackground.colorset/Contents.json
  UI/HPCommonUI/Resources/Assets.xcassets/HPColor/originSeparator.colorset/Contents.json
  UI/HPCommonUI/Sources/ViewController/BaseViewController.swift
Labels: ✨ Feature, 🤩 도현
